### ISSUE TITLE
Error while running all py

### ISSUE THREAD

**Issue by jatkarmandar** [zerothi/ts-tbt-sisl-tutorial#3]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    import sisl
  File "/home/mandar/.local/lib/python2.7/site-packages/sisl/__init__.py", line 93, in <module>
    from . import utils
  File "/home/mandar/.local/lib/python2.7/site-packages/sisl/utils/__init__.py", line 41, in <module>
    from . import mathematics as math
  File "/home/mandar/.local/lib/python2.7/site-packages/sisl/utils/mathematics.py", line 8, in <module>
    from sisl._indices import indices_le
ImportError: No module named _indices

**Comment by zerothi** [comment]
Could you please let us know how you have compiled sisl? It seems something has gone *very* wrong ;)

**Comment by zerothi** [comment]
I'll mark this as resolved since requester didn't return.
